name: LOG FORWARDING
label: AUDIT

description: |-
 Verify that rules have a LOG FORWARDING configured

type: pan_validation
labels:
  collection:
    - CYBERSECURITY

variables:

  - name: placeholder
    description: Some Parameter
    default: yes
    type_hint: hidden

snippets:
# test that all security policies have log forwarding configured
 - name: security_policy_test
   cmd: parse
   variable: config
   outputs:
     # get a list of security policies with a log forwarding configured
     - name: security_policies_with_log_forwarding
       capture_list: |-
         /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
         /rulebase/security/rules/entry/log-setting/../@name

     # get a list of security policies without Log Forwarding PANORAMA
     - name: log_forwarding_security_policies_without_PANORAMA_profile
       capture_list: |-
         /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
         /rulebase/security/rules/entry/log-setting[text()='PANORAMA']/../@name
       filter_items: item not in log_forwarding_security_policies_without_PANORAMA_profile
       
# check that all allow security policies have a Log Forwarding PANORAMA
  - name: security_policies_have_profile_log_forwarding_PANORAMA
    label: check that all security policies have a log forwarding PANORAMA
    test: security_policies_with_log_forwarding | length == 0
    severity: medium
    fail_message: |
      security policies without log forwarding PANORAMA: {{ log_forwarding_security_policies_without_PANORAMA_profile }}
    pass_message: |
      all security policies have a log forwarding PANORAMA
