name: LOG FORWARDING
label: AUDIT

description: |-
 Verify that rules have a LOG FORWARDING configured

type: pan_validation
labels:
  collection:
    - CYBERSECURITY

variables:

  - name: placeholder
    description: Some Parameter
    default: yes
    type_hint: hidden

snippets:
