name: LOG FORWARDING
label: AUDIT

description: |-
 Verify that rules have a LOG FORWARDING configured

type: pan_validation
labels:
  collection:
    - CYBERSECURITY

variables:

  - name: placeholder
    description: Some Parameter
    default: yes
    type_hint: hidden

snippets:

  # test that all allow security policies have a profile or profile-group configured
  - name: security_policy_test
    cmd: parse
    variable: config
    outputs:
      # get a list of security policies with a profile or group configured
      - name: security_policies_Log_Forwarding
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
          /rulebase/security/rules/entry/log-setting/../@name

      # get a list of security policies with action allow
      - name: security_policies_with_Log_Forwarding_ALERT
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']
          /rulebase/security/rules/entry/log-setting[text()='ALERT']/../@name
        filter_items: item not in security_policies_Log_Forwarding

  # check that all allow security policies have a Log Forwarding ALERT
  - name: check_allow_security_policies_have_profile
    label: check that all allow security policies have a Log Forwarding ALERT
    test: security_policies_with_Log_Forwarding_ALERT | length == 0
    severity: medium
    fail_message: |
      Security policies without Log Forwarding ALERT: {{ security_policies_with_Log_Forwarding_ALERT }}
    pass_message: |
      All security policies have a Log Forwarding ALERT
