name: audit-log-forwarding-enabled
label: AUDIT - LOG FORWARDING

description: |
  Make sur that all rules have a log forwarding enabled
  
type: pan_validation
labels:
  collection:
    - Cybersecurity
    - Audit

variables:

  - name: placeholder
    description: Some Parameter
    default: yes
    type_hint: hidden

snippets:

- name: parse config variable and capture outputs
    cmd: parse
    variable: config
    outputs:
      # create a variable named 'zone_names' which will be a list of the attribute 'names' from each zone
      # note the use of '//' in the capture_pattern to select all zones
      # the '@name' will return only the value of the attribute 'name' from each 'entry'
      - name: zone_names
        capture_pattern: /config/devices/entry/vsys/entry/zone//entry/@name
      # note here we can combine an advanced xpath query with 'capture_object'. This will capture
      # the full interface definition from the interface that contains the 'ip_to_find' value
      - name: interface_with_ip

- name: zones_are_configured
  cmd: validate
  label: Ensure at least one zone is Configured
  test: zone_names is not none
